Repository julia-vscode/SymbolServer.jl, pull requests merged in 2021-01, with the labels that each got.

#195 closes vscode issue #1832
  src/symbols.jl
  test/runtests.jl
Labels: bug

#193 make sure `_doc` always returns a String
  src/utils.jl
Labels: bug

#155 storage mechanism
  Project.toml
  src/SymbolServer.jl
  src/faketypes.jl
  src/serialize.jl
  src/server.jl
  src/symbols.jl
  src/utils.jl
Labels: enhancement

#199 add recursive_copy method
  src/utils.jl
Labels: bug

#202 Add registry indexer
  .gitignore
  registryindexer/Dockerfile
  registryindexer/Manifest.toml
  registryindexer/Project.toml
  registryindexer/main.jl
  src/indexbasestdlib.jl
  src/indexpackage.jl
  src/utils.jl
Labels: enhancement

#203 propogate get_return_types
  src/symbols.jl
Labels: bug

#209 Fix how server.jl loads SymbolServer.jl code
  src/server.jl
Labels: Showstopper, bug

#211 add Random.randn methods to Base
  src/symbols.jl
Labels: bug
